language: php

php:
  - 7.1

before_script:
  - composer self-update

install:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
