Reporters:
    type: entity
    table: reporters
    id:
        username:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            id: true
            generator:
                strategy: IDENTITY
    lifecycleCallbacks: {  }
