Roomspecialhours:
    type: entity
    table: roomspecialhours
    id:
        roomspecialhoursid:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        roomid:
            type: integer
            nullable: false
            options:
                unsigned: false
        fromrange:
            type: datetime
            nullable: false
            options:
                default: '''0000-00-00 00:00:00'''
        torange:
            type: datetime
            nullable: false
            options:
                default: '''0000-00-00 00:00:00'''
        start:
            type: time
            nullable: false
            column: START
        end:
            type: time
            nullable: false
            column: END
    lifecycleCallbacks: {  }
