Settings:
    type: entity
    table: settings
    id:
        settingname:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        settingvalue:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
    lifecycleCallbacks: {  }
