Users:
    type: entity
    table: users
    id:
        username:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        password:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: PASSWORD
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        lastlogin:
            type: datetime
            nullable: false
            options:
                default: current_timestamp()
        active:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: '''0'''
    lifecycleCallbacks: {  }
